spring.application.name=exam-system-member6

# 1. Enable the browser database dashboard
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. Set up your private in-memory H2 database
spring.datasource.url=jdbc:h2:mem:isolateddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Tell Hibernate to build your tables automatically
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true